"""Initial migration

Revision ID: d52a6f4b5682
Revises: 
Create Date: 2024-07-25 00:54:07.064897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd52a6f4b5682'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contact')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('contact_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['user.id'], name='contact_contact_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='contact_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='contact_pkey')
    )
    # ### end Alembic commands ###
